# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '百度地图_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 百度地图_Demo
  pod 'BaiduMapKit' #百度地图SDK
end
